(() => {
  const esc2 = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n2 = x => x == null || Number.isNaN(Number(x)) ? '—' : Number(x).toLocaleString(undefined,{maximumFractionDigits:2});
  const m2 = x => x == null || Number.isNaN(Number(x)) ? '—' : Number(x).toLocaleString(undefined,{maximumFractionDigits:8});
  const pill2 = a => { const s=String(a||'NEUTRAL'); const cls=/BULLISH|POSITIVE/.test(s)?'bull':/BEARISH|NEGATIVE/.test(s)?'bear':'neutral'; return `<span class="pill ${cls}">${esc2(s)}</span>`; };
  const card2 = (l,v,s='') => `<div class="card metric-card"><div class="muted">${esc2(l)}</div><strong>${v}</strong><span>${esc2(s)}</span></div>`;
  async function get2(u){ const r=await fetch(u); if(!r.ok){let d={};try{d=await r.json()}catch{} throw Error(d.detail||'Unable to load live intelligence.');} return r.json(); }
  window.fusedSignal = async function(symbol, chain='', token='') {
    symbol=(symbol||'BTCUSDT').toUpperCase().trim(); chain=(chain||'').trim(); token=(token||'').trim();
    const C=document.getElementById('content'),T=document.getElementById('title'),U=document.getElementById('updated');
    T.textContent=`${symbol} — Unified Signal`; C.innerHTML=`<div class="loading"><div class="spinner"></div><b>Building unified signal…</b><span>Binance + technicals + on-chain + liquidity + contract risk</span></div>`;
    try {
      const q=new URLSearchParams({interval:document.getElementById('fusionInterval')?.value||'1h'}); if(chain&&token){q.set('chain',chain);q.set('token',token)}
      const r=await get2(`/api/crypto/${encodeURIComponent(symbol)}/fused?${q}`); U.textContent='LIVE • '+new Date().toLocaleTimeString();
      const c=r.components||{}, oc=r.onchain||{}, occ=oc.components||{}; const dataMode=r.data_mode||'market-only';
      C.innerHTML=`<div class="hero"><div><div class="eyebrow">${dataMode==='multi-source'?'MULTI-SOURCE LIVE INTELLIGENCE':'MARKET INTELLIGENCE'}</div><h2>${esc2(r.symbol)}</h2><p>${dataMode==='multi-source'?'Market, technical, on-chain, liquidity and contract-risk evidence have been fused into one research score.':'Add a token contract below to activate live on-chain, liquidity and contract-risk scoring.'}</p></div><div class="scorebox">${pill2(r.bias)}<strong>${n2(r.score)}<small>/100</small></strong><span>${n2(r.confidence)}% model confidence</span></div></div>
      <div class="grid">${card2('Trend',n2(c.trend),'Technical · 20%')}${card2('Momentum',n2(c.momentum),'Technical · 18%')}${card2('Volume',n2(c.volume),'Technical · 12%')}${card2('Volatility',n2(c.volatility),'Technical · 8%')}${card2('On-chain',n2(c.onchain),'On-chain · 25%')}${card2('DEX liquidity',n2(c.liquidity),'Liquidity · 10%')}${card2('Contract safety',n2(c.safety),'Safety · 7%')}</div>
      <section class="panel"><div class="panel-head"><h3>Token contract context</h3><span class="tag">${dataMode==='multi-source'?'CONNECTED':'OPTIONAL'}</span></div><div class="inline"><select id="fusionChain"><option value="ethereum">Ethereum</option><option value="base">Base</option><option value="arbitrum">Arbitrum</option><option value="optimism">Optimism</option><option value="polygon">Polygon</option><option value="bnb">BNB Chain</option></select><input id="fusionToken" placeholder="0x token contract address" value="${esc2(token)}"><button onclick="fusedSignal(document.getElementById('fusionSymbol').value,document.getElementById('fusionChain').value,document.getElementById('fusionToken').value)">Recalculate</button></div><p class="muted">Use the token contract corresponding to the asset. On-chain results are estimates from available public/indexed data.</p></section>
      <section class="panel"><div class="panel-head"><h3>Evidence breakdown</h3><span class="tag">${dataMode.toUpperCase()}</span></div><div class="bars">${Object.entries(c).map(([k,v])=>`<div class="barrow"><span>${esc2(k)}</span><div class="bar"><i style="width:${Math.min(100,Math.max(0,Number(v)||0))}%"></i></div><b>${n2(v)}</b></div>`).join('')}</div></section>
      ${dataMode==='multi-source'?`<div class="two"><section class="panel"><div class="panel-head"><h3>On-chain evidence</h3><span class="muted">${esc2(oc.label||'')}</span></div><div class="grid">${card2('Transfer flow',n2(occ.transfer_flow),'Observed')}${card2('Whale activity',n2(occ.whale_activity),'Observed')}${card2('Holder concentration',n2(occ.holder_concentration),'Observed')}${card2('DEX liquidity',n2(occ.dex_liquidity),'Observed')}${card2('Contract safety',n2(occ.contract_safety),'Heuristic')}</div>${(oc.reasons||[]).slice(0,5).map(x=>`<div class="reason">✓ ${esc2(x)}</div>`).join('')}${(oc.risks||[]).slice(0,5).map(x=>`<div class="reason risk">! ${esc2(x)}</div>`).join('')}</section><section class="panel"><div class="panel-head"><h3>Technical evidence</h3><span class="muted">${esc2(r.interval||'1h')}</span></div><div class="grid">${card2('Price','$'+m2(r.raw?.price),'Latest')}${card2('RSI',n2(r.raw?.rsi),'Momentum')}${card2('7D return',n2(r.raw?.ret_7d)+'%','Recent')}${card2('30D return',n2(r.raw?.ret_30d)+'%','Recent')}</div></section></div>`:''}
      <div class="notice"><b>Research-only:</b> This is a heuristic analytical model. On-chain data may be incomplete; contract safety is not a security audit; signals are not financial advice.</div>`;
      if(document.getElementById('fusionChain')) document.getElementById('fusionChain').value=chain||'ethereum';
    } catch(e) { C.innerHTML=`<div class="empty"><b>Unified signal unavailable</b><span>${esc2(e.message)}</span><button onclick="liveTerminal()">Back to terminal</button></div>`; }
  };
  window.liveTerminal = function(){
    const C=document.getElementById('content'),T=document.getElementById('title'); T.textContent='Live Signal Terminal';
    C.innerHTML=`<div class="hero"><div><div class="eyebrow">MULTI-SOURCE SIGNAL ENGINE</div><h2>Unified market intelligence</h2><p>Combine live Binance market data with technical analysis and, when available, token-level on-chain intelligence.</p></div></div><section class="panel"><div class="panel-head"><h3>Analyze asset</h3><span class="tag">FREE DATA</span></div><div class="inline"><input id="fusionSymbol" value="BTCUSDT" placeholder="BTCUSDT"><select id="fusionInterval"><option>1h</option><option>15m</option><option>5m</option><option>4h</option><option>1d</option></select><button onclick="fusedSignal(document.getElementById('fusionSymbol').value)">Market-only signal</button></div><div class="inline" style="margin-top:10px"><select id="quickChain"><option value="ethereum">Ethereum</option><option value="base">Base</option><option value="arbitrum">Arbitrum</option><option value="optimism">Optimism</option><option value="polygon">Polygon</option><option value="bnb">BNB Chain</option></select><input id="quickToken" placeholder="Optional token contract 0x…"><button onclick="fusedSignal(document.getElementById('fusionSymbol').value,document.getElementById('quickChain').value,document.getElementById('quickToken').value)">Full multi-source signal</button></div></section><section class="panel"><div class="panel-head"><h3>Scoring model</h3></div><div class="stack"><div><b>Trend · 20%</b><span>EMA structure and directional regime</span></div><div><b>Momentum · 18%</b><span>RSI and MACD confirmation</span></div><div><b>Volume · 12%</b><span>Activity versus baseline</span></div><div><b>Volatility · 8%</b><span>Market risk conditions</span></div><div><b>On-chain · 25%</b><span>Transfer flow, whale activity and holder concentration</span></div><div><b>DEX liquidity · 10%</b><span>Available liquidity across observed pools</span></div><div><b>Contract safety · 7%</b><span>Bytecode heuristics; not a security audit</span></div></div></section>`;
  };
})();
